### PR TITLE
Updated installation script

### LINKED ISSUE #83: Update installation script for v0.2.0
# Goal

The installation script still produces files with explicit version `0.1.0` in file names, this needs to be changed.

# Plan

Either:

1. Change to be v0.2.0; or
1. Remove version-specific naming for PosturePerfection items

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- Update the install script to use v0.2.0
-  Still need to create the assets and ensure they match the links in this script

# Screenshots/Gif (if appropriate)

It can sometimes be useful to add a screenshot or animated gif to demonstrate new functionality

# Checklist

## Code
N/A

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #83

### CODE REVIEW

**Review by C-Begley — APPROVED** [review]
Looks good, although it looks like there is a commit to main that has included some of these changes?

**Review by Andrew-Ritchie — APPROVED** [review]
This looks good, will this need updated to work on Mac?

**Review by miklasr — APPROVED** [review]
Cool

**Comment by Ashwin-MJ** [comment]
> This looks good, will this need updated to work on Mac?

Currently we've not said that PosturePerfection is supported on Mac, but yeah we might need to fix a few things. Can look into this in a future issue

**Pull request merged**
