### PR TITLE
16 Initial GUI Development

### PR DESCRIPTION
**Pull request by Andrew-Ritchie**
# Details

- Created MakeFile for the user interface that is compatible with the Raspberry Pi.
- Decided on technologies for the UI.
- Developed the initial GUI using the QT API. This includes scalable features, the current date and time, interactive buttons and a placeholder for the live feed.

# Screenshots

Screenshot 2021-03-01 at 02 13 40

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass by running `./test.sh`

## Documentation
- [ ] I have updated documentation appropriately (GitHub Pages)
- [ ] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes Issue #16

### CODE REVIEW

**Review by Ashwin-MJ — COMMENTED** [review]
There seems to be quite a bit of unnecessary whitespace/new lines, do you mind removing that just to keep things tidy 😅 (Btw i don't think you pushed your update to the gitignore)

**Review by Ashwin-MJ — APPROVED** [review]
Looks great as a starting point to me! I think you might need to remove the `src/gui/postureperfection` binary as well but other than that I'm happy to merge

**Comment by Andrew-Ritchie** [comment]
Thanks @Ashwin-MJ I have updated the gitignore and pushed it. I have also removed a lot of the whitespace!

**Comment by miklasr** [comment]
I get:
```
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
```
I guess I'm missing QT, so this should probably be added to the install script, right?

**Comment by miklasr** [comment]
I had to run:
```sh
sudo apt install qt5-default
```
and
```sh
sudo apt install libqcustomplot-dev
```
for it to build.

Could we add:
```
sudo apt install -y qt5-default libqcustomplot-dev
```
to the `install_dependencies.sh` script?

**Comment by Andrew-Ritchie** [comment]
Thanks @miklasr, I have updated the install dependencies file to include this! :)

**Comment by miklasr** [comment]
cpplint output:
```
./main.cpp:29:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
./main.cpp:33:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
./main.cpp:35:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
Done processing ./main.cpp
./mainwindow.cpp:32:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
./mainwindow.cpp:34:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
./mainwindow.cpp:36:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
./mainwindow.cpp:63:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
./mainwindow.cpp:108:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
Done processing ./mainwindow.cpp
./mainwindow.h:66:  Constructors callable with one argument should be marked explicit.  [runtime/explicit] [5]
Done processing ./mainwindow.h
Total errors found: 9
```

**Review by miklasr — APPROVED** [review]
Very nice, thanks for making those changes.

**Review by C-Begley — APPROVED** [review]

**Pull request merged**
