### PR TITLE
Gui update

### LINKED ISSUE #89: Tidy up GUI
# Goal

Ensure the GUI has been cleaned up a little

# Additional information

- Ensure text scales up with screen size
- Ensure buttons scale up with screen size -- maybe add extra padding to buttons
- Ensure contrast between text and background is sufficient -- there is currently some dark on dark text
- etc.

### PR DESCRIPTION
**Pull request by miklasr**
# Details

- Overhauled GUI
- Increased size of widgets
- Most widgets now resizeable
- Add "help and about" page
- Move most styling to qss stylesheet

# Screenshots/Gif (if appropriate)

home
settings
about

# Checklist

## Code
- [ ] ~I have added some tests~
- [x] I have run the tests locally to ensure they all pass by running `.scripts/build.sh -enable-testing`

## Documentation
- [x] I have updated documentation appropriately (Doxygen)
- [ ] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #89

### CODE REVIEW

**Comment by C-Begley** [comment]
Perhaps we can have Set Posture to update to Reset Posture once it has been set for the first time

**Comment by C-Begley** [comment]
I don't know if it easy to set the logo on the task bar in QT but that might be good to set also

**Comment by miklasr** [comment]
The qss stylesheet is currently within the gui directory. We will need to move this to a separate high-level directory to facilitate releases. This is out of the issue's scope and tracked in #133.

**Comment by C-Begley** [comment]
Should we define ideal posture better or include a link to a reputable posture guide?

**Review by Ashwin-MJ — COMMENTED** [review]
Looks good, only thing is on my Pi the text for "Set Ideal Posture" and the first line of the subtitle "Set current posture as my target" seem to overlap

**Comment by Ashwin-MJ** [comment]
Oh also, do we want to add a page to the documentation with some screenshots of the GUI? This could be the start of the "manual" you were talking about which we can do next week, would be helpful if the screenshots were added with this PR though

**Comment by miklasr** [comment]
> Should we define ideal posture better or include a link to a reputable posture guide?

Shall we move that to a separate issue, perhaps one of the documentation issues?

**Comment by miklasr** [comment]
> Looks good, only thing is on my Pi the text for "Set Ideal Posture" and the first line of the subtitle "Set current posture as my target" seem to overlap

@Ashwin-MJ, thanks for spotting that. I've reworked the resizing logic to take height into account and generally refactored that code a little. Should all be fixed now.

**Review by Ashwin-MJ — APPROVED** [review]

**Review by Andrew-Ritchie — APPROVED** [review]
Brilliant work, looks really good! :)

**Review by C-Begley — APPROVED** [review]

**Comment by C-Begley** [comment]
> > Should we define ideal posture better or include a link to a reputable posture guide?
> 
> Shall we move that to a separate issue, perhaps one of the documentation issues?

Yeah, happy to do that

**Pull request merged**
