### PR TITLE
Smoothing

### LINKED ISSUE #94: Adjust smoothing settings when frame rate is changed
# Goal

Adjust IIR smoothing settings when the frame rate is increased or decreased. This may require modification of the increments to be used inside the `increase`/`decrease_framerate` functions.

# Plan

- Consider simplest method for finding appropriate smoothing settings
- Probably pre-computed -- taken from scipy or similar
- Consider how many to pre-compute and what data structure to store these in
- Could possibly use closest known values if we want to pre-compute fewer.

### PR DESCRIPTION
**Pull request by miklasr**
# Details

- Rework IIR code to set the filters to the first frame received, i.e., not staring from a zero initial state anymore
- Create `FramerateSettings` class to allow easier changing of the frame rate and any associated parameters like IIR smoothing coefficients
- Make GUI display actual set frame rate on start instead of a placeholder value

# Checklist

## Code
- [ ] ~I have added some tests~
- [x] I have manually tested the additions
- [x] I have run the tests locally to ensure they all pass by running `.scripts/build.sh -enable-testing`

## Documentation
- [x] I have updated documentation appropriately (Doxygen)
- [ ] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #94

### CODE REVIEW

**Review by Andrew-Ritchie — APPROVED** [review]
This looks good to me, nice job!

**Comment by Andrew-Ritchie** [comment]
After a full build with testing enabled i did get a segmentation fault on the raspberry pi on the first run but apart from that it runs and the feed is much smoother!

**Comment by Andrew-Ritchie** [comment]
After building and running the branch I do get a segmentation fault on the first run. When I build the branch on the Raspberry Pi with testing enabled, it fails constantly on the fifth test (see attachment) which could be related?

Screenshot 2021-04-05 at 10 58 39

**Review by Ashwin-MJ — COMMENTED** [review]
Code looks really good, and I didn't have the issue with testing that Andrew mentioned. I get a seg fault the first time i run the application though, and this seems consistent across branches so we should try and fix that. Other than that the smoothing looks great! Look forward to plugging it in to my PR as well 😄

**Review by Ashwin-MJ — APPROVED** [review]
I tested on my Pi with a fresh clone and I did not have a seg fault, and all tests passed. Setting frame rates works well, although on the Pi I can only really test 1.0, 1.5 and 2.0 fps

**Comment by miklasr** [comment]
> After building and running the branch I do get a segmentation fault on the first run. When I build the branch on the Raspberry Pi with testing enabled, it fails constantly on the fifth test (see attachment) which could be related?
> 
> Screenshot 2021-04-05 at 10 58 39

@Andrew-Ritchie, as Ashwin didn't have this problem with a fresh install on the Pi, and I didn't have this problem on my laptop, would you be happy for me to merge?

**Review by Andrew-Ritchie — APPROVED** [review]
Yes @miklasr, this appears to be an issue not related to your branch. When I run it on my Pi the smoothing works really well, Good Job! :)

**Review by C-Begley — COMMENTED** [review]
Looks good to me. Definitely nicer with the smoothing

**Pull request merged**
