### PR TITLE
Display partial pose if there are consecutive Trustworthy joints

### LINKED ISSUE #129: Display a partial pose on the output
# Goal

Display a partial pose on the output. If any of the segments can be displayed, they should (accompanied by a good/bad posture). The intention is that the user gets more feedback on what the system can see.

# Additional information

If any segment can be plotted, i.e., two consecutive nodes are `Trustworthy`, the segment should be plotted.

An undefined output should only be generated when there are no consecutive nodes that are `Trustworthy`.

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- Previously we were displaying `Undefined` if any of the joints were `Untrustworthy` but this has been changed to allow the displaying of partial poses

# Checklist

## Code
- [x] I have added some tests
- [x] I have run the tests locally to ensure they all pass by running `.scripts/build.sh -enable-testing`

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #129

### CODE REVIEW

**Comment by Andrew-Ritchie** [comment]
Looks great, just checking if there is an undefined output with some nodes detected it should be blue on the video feed?

Screenshot 2021-04-08 at 09 40 08

**Review by C-Begley — APPROVED** [review]
Tested on Laptop and PI and looks to be running well

**Review by Andrew-Ritchie — APPROVED** [review]
Looks great, it's working for me no problem.

Screenshot 2021-04-08 at 13 12 52

**Comment by miklasr** [comment]
I encountered a scenario where only the head segment was detected. This segment showed up as green. There were no other segments in red (this was evident because there were no arrows). The status remained red/bad during this time.

I think the problem may be that the system checks that all segments have a good posture, even if some segments are untrustworthy.

**Review by miklasr — COMMENTED** [review]
This all looks really good and I'm happy to merge subject to the outcome of the discussion on what should be output when a single segment is output.

**Review by miklasr — APPROVED** [review]
Awesome! This works very well now, giving the use informative feedback for partially recognised posture.

**Review by Andrew-Ritchie — APPROVED** [review]
This is working well for me, good job! :)

**Review by C-Begley — APPROVED** [review]

**Pull request merged**
