### PR TITLE
Initial UML Diagram

### LINKED ISSUE #25: Design UML diagrams and Interfaces
# Goal
Create UML diagrams to better understand subsystem interactions

### PR DESCRIPTION
**Pull request by C-Begley**
# Details

- Added initial UML diagram

# Screenshots/Gif (if appropriate)
Screenshot from 2021-02-05 13-18-20

Screenshot from 2021-02-05 13-09-49

It can sometimes be useful to add a screenshot or animated gif to demonstrate new functionality

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

closes #25

### CODE REVIEW

**Review by miklasr — APPROVED** [review]
Looks like a very good place to start from, nice!

**Review by Ashwin-MJ — APPROVED** [review]
Nice!

**Comment by Andrew-Ritchie** [comment]
Looks great!

**Review by Andrew-Ritchie — APPROVED** [review]
Looks great!

**Comment by C-Begley** [comment]
Forgot to add commit for actual file changes

**Pull request merged**
