### PR TITLE
Initial Wireframes

### PR DESCRIPTION
**Pull request by Andrew-Ritchie**
# Details

- Created initial wireframes.
- Discussed wireframes with the team.
- Create a wireframe page on GitHub pages. 
- Added wireframe descriptions to GitHub pages. 

# Screenshots

ScreenShot
ScreenShot
ScreenShot

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes Issue #28

### CODE REVIEW

**Review by Ashwin-MJ — COMMENTED** [review]
Looks good, did you manage to test this locally to ensure the GitHub Pages looks how you want it to? (If so just tick the check boxes in the PR template)

**Review by miklasr — COMMENTED** [review]
This is what you showed us this morning, right? Just checking that it definitely loaded correctly on GH Pages.

**Comment by Andrew-Ritchie** [comment]
Yes, this is what I showed you this morning, it runs locally but I will add screenshots into this PR to confirm how they look!

**Review by Ashwin-MJ — APPROVED** [review]
Nice! Looks like a good starting point for the GUI

**Review by C-Begley — APPROVED** [review]
Look good to me

**Review by miklasr — APPROVED** [review]

**Pull request merged**
