### PR TITLE
GitHub Pages updates

### LINKED ISSUE #8: Add spec to GitHub Pages

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- Added the specification we outlined on MS Teams to the GitHub Pages
- Restructured the order of pages
- Added some nicer headers
- Added some content to the "Welcome" page

# Screenshots/Gif (if appropriate)

Screenshot 2021-02-03 at 17 30 19
Screenshot 2021-02-03 at 17 30 26
Screenshot 2021-02-03 at 17 30 34
Screenshot 2021-02-03 at 17 33 48

# Checklist

## Code
- [ ]  ~I have added some tests~
- [ ] ~I have run the tests locally to ensure they all pass~

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes Issue #8

### CODE REVIEW

**Review by miklasr — APPROVED** [review]
Very nice

**Review by C-Begley — APPROVED** [review]
Looks good to me

**Review by Andrew-Ritchie — APPROVED** [review]
Looks great!

**Comment by Ashwin-MJ** [comment]
Closes #8

**Pull request merged**
