### PR TITLE
71 refactor posture

### LINKED ISSUE #71: Refactor Posture Estimator Code
# Goal
Update Posture Estimator to be better suited to pipeline

# Plan

1. Currently we use an array and joint pointers, but only need the array, so remove pointers and use indexes
2. Output should be a frame containing all info about posture estimator

# Additional information

Any other useful information (if appropriate)

### PR DESCRIPTION
**Pull request by C-Begley**
# Details

- Removed pointed to upper and lower joints
- Added a new struct to represent the posture output
- Removed pointers in Pose structs

# Screenshots/Gif (if appropriate)

# Checklist

## Code
- [x] I have added some tests
- [x] I have run the tests locally to ensure they all pass by running `.scripts/build.sh -enable-testing`

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #71

### CODE REVIEW

**Comment by miklasr** [comment]
Could you merge with main to make sure the diffs are up to date?

**Review by miklasr — APPROVED** [review]
Nice!

**Review by Andrew-Ritchie — COMMENTED** [review]
Have you tested these changes run with the current GUI? :)

**Review by Ashwin-MJ — APPROVED** [review]

**Comment by C-Begley** [comment]
> Have you tested these changes run with the current GUI? :)
Yes, it works the same

**Review by Andrew-Ritchie — APPROVED** [review]
Awesome, looks great! :)

**Pull request merged**
