### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- Included sequence diagram and a corresponding page explaining it to the docs
- Slight fixes to the `system-diagram` page (I'm not sure exactly how much of this will actually be used in the future. Should I leave it in for now?)
- Updated the logo for Doxygen so that it sizes correctly

Let me know if there are any other changes to be made around the docs and I will make them within this PR :)

This is the sequence diagram i refer to in the documentation:
sequence-diagram

# Checklist

## Code
N/A

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

### CODE REVIEW

**Review by C-Begley — APPROVED** [review]
All looks good to me. The stuff I've done in what is now system-design.md will have to be changed to match the new sequence diagram though.

**Review by Andrew-Ritchie — APPROVED** [review]
Looks great!

**Comment by Ashwin-MJ** [comment]
> All looks good to me. The stuff I've done in what is now system-design.md will have to be changed to match the new sequence diagram though.

Shall I just go ahead and update this right now so that we don't forget in the future?

**Comment by C-Begley** [comment]
> > All looks good to me. The stuff I've done in what is now system-design.md will have to be changed to match the new sequence diagram though.
> 
> Shall I just go ahead and update this right now so that we don't forget in the future?

You can do, although do we need a discussion as a team for the UML diagram and division of work? Might be best to have everyone involved/ on the same page?

**Comment by Ashwin-MJ** [comment]
I've updated the sequence diagram and documentation after our meeting today (see the updated image in the initial PR comment). We could either:
1. Leave this PR open for now, and I will add UML diagrams for the various components after we have defined them in the next few days. 
2. Merge this PR and people add UML diagrams to the documentation as part of their PR for defining the interface of each component.

I don't mind either way, but 2 is probably better to split up tasks. I suggest we use something like [PlantUML](https://plantuml.com/object-diagram) for making the UML diagrams though and we can add them to the directory I added here so they can be modified easily in the future

**Review by miklasr — APPROVED** [review]

**Comment by Ashwin-MJ** [comment]
I created an initial class diagram with the various components we have defined and embedded it within the `Class Diagram` page. The PDF is below:

[class-diagram.pdf](https://github.com/ESE-Peasy/PosturePerfection/files/6002774/class-diagram.pdf)

And this is how it renders on GitHub Pages (you can scroll and zoom etc within the browser):

Screenshot 2021-02-18 at 12 40 26

**Review by miklasr — APPROVED** [review]

**Review by C-Begley — COMMENTED** [review]
There's alot of .html files. Should they be in git ignore? Are they generated again by github sites

**Pull request merged**
