### PR TITLE
Initial model testing

### LINKED ISSUE #34: Wrapper class for interfacing with ML models
# Goal

Write a class to wrap around use of the ML model. This could be an abstract class with an implementation for use with TensorFlow Lite.

# Plan

1. Create a generic wrapper class to run the ML model
1. The input should be the current video frame
1. The output should be a structure containing the location of different body parts (the nodes of the stick person). The structure will be worked on for #17 

# Further
- [ ] Ensure output from C++ code matches the Python output for the pre-trained model (sanity check)

### PR DESCRIPTION
**Pull request by miklasr**
# Details

- Add a class for the core inference steps
- Wraps the complexity of the TensorFlow Lite C++ API

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes #34

### CODE REVIEW

**Comment by miklasr** [comment]
@Ashwin-MJ,
The CMake will not pass yet, because the TFL library is not available on the Actions runner. Three options come to mind:
1. Clone TFL into the runner for compiling our code
    - Seems like a bad idea, because it will probably make the runner very slow
1. Compile an .so of the TFL library for both x86 and RPi (ARM) and provide them with our repo
     - Some `#define`s would be used to pick the right on based on architecture
     - I think the preferred option
1. Ignore the failing CI
    - Probably the worst option

What do you think?

**Comment by Ashwin-MJ** [comment]
> 1. Clone TFL into the runner for compiling our code
>    
>    * Seems like a bad idea, because it will probably make the runner very slow

Yeah I'd agree we should probably try and avoid this
> 2. Compile an .so of the TFL library for both x86 and RPi (ARM) and provide them with our repo
>    
>    * Some `#define`s would be used to pick the right on based on architecture
>    * I think the preferred option

This would be great, but personally I'm not entirely sure how we go about doing that. Do you have an idea how to do it?
> 3. Ignore the failing CI
>    
>    * Probably the worst option

Yeah I would prefer at least trying option 1 over ignoring the failing CI altogether.

**Comment by miklasr** [comment]
@Ashwin-MJ, looky here it works! Would you prefer the build step to be removed from here, so we get quicker completion of the pipelines? Keeping it in would give us a bit more insurance that everything we pushes works though. We may need to build if we want to run tests via CMake, but possibly don't need to build with TFL, which is what takes all the time.

I'm just updating documentation and then I'll open it up for review.

**Review by Ashwin-MJ — APPROVED** [review]
Awesome! Great stuff getting it sorted to work with GitHub actions! Regarding your comment, I think we will need to keep it in for if we do any "integration" tests using TFL, but for unit tests just testing the various components of our project, we might not need it. 

I'd say let's keep it in for now for the insurance that future changes don't break the system. Can always change our minds later on.

I've already reviewed the code so happy with that, will let the others have a more thorough review of it.

**Comment by C-Begley** [comment]
>     2\. Compile an .so of the TFL library for both x86 and RPi (ARM) and provide them with our repo

Code looks fine. I'll admit I don't understand it all. But a .so file is a compiled library right? Does that go against the ethos of not having compiled files on Git?

**Comment by miklasr** [comment]
> > ```
> > 2\. Compile an .so of the TFL library for both x86 and RPi (ARM) and provide them with our repo
> > ```
> 
> Code looks fine. I'll admit I don't understand it all. But a .so file is a compiled library right? Does that go against the ethos of not having compiled files on Git?

It's a bit of a contentious question. Generally, yes it's better not to have binaries in the main git repo. However, an acceptable situation might be to host a binary as a package/release or something similar so people can download it as part of our build process. Anyway We've ended up not doing that now.

**Pull request merged**
